### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by gotschmarcel** [MacDownApp/macdown#222]
Sometimes when an image has changed it is really annoying that MacDown has no button for reloading cached images.

**Comment by georgecrawford** [comment]
I've been annoyed by this as well. I can understand a latency updating remote images, but for local files referenced with relative paths, it would be great if a change to the last-modified date could trigger a reload.

**Comment by keenscribbler** [comment]
I'd also be very happy if this gets changed. Sometimes the caching persists even over restarts of the application. This changed my workflow so much hat I actually started to double check my images all the time.

**Comment by mmzoo** [comment]
As a workaround, I add `?some=thing` `?some=thing2` and `?some=thing3` etc. whenever I need to reload the image. That's at least faster than restarting the application.

**Comment by keenscribbler** [comment]
Thanks for the workaround @mmzoo. Works like a charm and is much less annoying than renaming the files or restarting the application.

**Comment by LandonSchropp** [comment]
It would be nice if this issue were reopened. Adding a query parameter to the file name isn't intuitive.

**Comment by csinva** [comment]
Fixing this issue would be amazing!

**Comment by uranusjr** [comment]
Wait no, this is a different issue. Sorry.

**Comment by uranusjr** [comment]
Fixed in #747. 🎈🎈🎈

**Comment by working-name** [comment]
Issue still present in 0.7.1 (870) on 10.12.6 unfortunately. Maybe that private API got renamed or something?
