### ISSUE TITLE
command-line utility doesn't create new file

### ISSUE THREAD

**Issue by franklinyu** [MacDownApp/macdown#672]
According to [the Wiki](https://github.com/MacDownApp/macdown/wiki/Advanced-Usage), the command-line utility should create a new file when the file doesn't exist. However on my machine (El Capitan) it only works when MacDown is not already running. This holds whether "Ensure open document on launch" is checked.

**Comment by uranusjr** [comment]
Oops, this is an oversight on my part. I implemented the auto creation hook, but put them during the application launch sequence, so it’s only run when MacDown isn’t already running…

**Comment by franklinyu** [comment]
There is still an issue. In a clean folder when I do

```shell
$ macdown README.markdown
```

then MacDown opened a new window with title `README.markdown` as expected. However if I save the file immediately, the default filename becomes `README.md`; I expected it to preserve the filename extension `.markdown`.

**Comment by uranusjr** [comment]
This is actually a different problem, but still a problem. Fixed.
