### ISSUE TITLE
${Product_Name} missing

### ISSUE THREAD

**Issue by holzhannes** [MacDownApp/macdown#805]
Version 0.7.

After the update to 0.7 the product_name is missing, switched back to 0.6.4
![view](https://cloud.githubusercontent.com/assets/4320619/25990064/a96b61ca-36fe-11e7-9c64-16f86ff31eec.png)

**Comment by uranusjr** [comment]
This is a translation issue, and should not affect normal functionalities. I just fixed it with the latest commit, will release a new version later today or tomorrow.

**Comment by uranusjr** [comment]
Fixed in 0.7.1.

**Comment by kimasendorf** [comment]
Just updated to 0.7.1 but the ${PRODUCT_NAME} issues is still there. I am on El Capitan.

**Comment by uranusjr** [comment]
Because I released a wrong binary, just realised myself. Sorry. 😱 

Will update the release tonight.

**Comment by uranusjr** [comment]
I just pushed a new release. The correct build number should be 870. You can check this in the update dialog.

![The correct 0.7.1 binary](https://cloud.githubusercontent.com/assets/605277/26052135/0bff1b70-3997-11e7-8b1c-aa19ee1a3e34.png)

**Comment by kimasendorf** [comment]
working now! thx =)
